//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AmonicEntities : DbContext
    {
        public AmonicEntities()
            : base("name=AmonicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airports> Airports { get; set; }
        public virtual DbSet<AnswerOptions> AnswerOptions { get; set; }
        public virtual DbSet<AnswersToQuestions> AnswersToQuestions { get; set; }
        public virtual DbSet<CabinTypes> CabinTypes { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<Surveys> Surveys { get; set; }
    }
}
