//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswersToQuestions
    {
        public int SurveyId { get; set; }
        public int QuestionId { get; set; }
        public int AnswerOptionId { get; set; }
    
        public virtual AnswerOptions AnswerOptions { get; set; }
        public virtual Questions Questions { get; set; }
        public virtual Surveys Surveys { get; set; }
    }
}
