//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surveys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Surveys()
        {
            this.AnswersToQuestions = new HashSet<AnswersToQuestions>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DepartureId { get; set; }
        public Nullable<int> ArrivalId { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> CabinTypeId { get; set; }
        public string GenderCode { get; set; }
    
        public virtual Airports Airports { get; set; }
        public virtual Airports Airports1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswersToQuestions> AnswersToQuestions { get; set; }
        public virtual CabinTypes CabinTypes { get; set; }
        public virtual Genders Genders { get; set; }
    }
}
